// Device-native audio effects and non-cloud text-to-speech.
let audioCtx: AudioContext | null = null;
function getAudioContext(): AudioContext { if (!audioCtx) { const Context = window.AudioContext || (window as unknown as { webkitAudioContext: typeof AudioContext }).webkitAudioContext; audioCtx = new Context(); } if (audioCtx.state === 'suspended') void audioCtx.resume(); return audioCtx; }
function playNotes(notes: number[], type: OscillatorType, spacing: number, duration: number): void { try { const ctx = getAudioContext(); notes.forEach((frequency, index) => { const oscillator = ctx.createOscillator(); const gain = ctx.createGain(); const at = ctx.currentTime + index * spacing; oscillator.type = type; oscillator.frequency.setValueAtTime(frequency, at); gain.gain.setValueAtTime(.24, at); gain.gain.exponentialRampToValueAtTime(.01, at + duration); oscillator.connect(gain); gain.connect(ctx.destination); oscillator.start(at); oscillator.stop(at + duration); }); } catch { /* Audio is optional. */ } }
export const playSound = { pop: () => playNotes([400, 800], 'sine', .06, .12), success: () => playNotes([523.25, 659.25, 783.99, 1046.5], 'triangle', .08, .2), badge: () => playNotes([440, 554.37, 659.25, 880], 'sine', .1, .3) };
function voiceScore(voice: SpeechSynthesisVoice): number { const name = voice.name.toLowerCase(); const locale = voice.lang.toLowerCase(); return (locale.startsWith('en-za') ? 100 : 0) + (/(natural|enhanced|premium|neural|siri|google)/.test(name) ? 20 : 0) + (voice.localService ? 4 : 0); }
function preferredVoice(): SpeechSynthesisVoice | undefined { const voices = window.speechSynthesis.getVoices().filter(voice => voice.lang.toLowerCase().startsWith('en-')); return voices.sort((a, b) => voiceScore(b) - voiceScore(a))[0]; }
/** Speaks with a local South African English voice when the device supplies one; otherwise chooses its best natural English voice. */
export function speakText(text: string, onEnd?: () => void): void { if (!('speechSynthesis' in window) || !text.trim()) return; window.speechSynthesis.cancel(); const utterance = new SpeechSynthesisUtterance(text); const voice = preferredVoice(); if (voice) { utterance.voice = voice; utterance.lang = voice.lang; } else utterance.lang = 'en-ZA'; utterance.rate = .94; utterance.pitch = 1.03; utterance.onend = () => onEnd?.(); utterance.onerror = () => onEnd?.(); window.speechSynthesis.speak(utterance); }
/** Call from a user interaction to make browser voice availability more reliable on mobile devices. */
export function warmUpSpeechVoices(): void { if ('speechSynthesis' in window) window.speechSynthesis.getVoices(); }
export function stopSpeech(): void { if ('speechSynthesis' in window) window.speechSynthesis.cancel(); }
