import { useRef, useState, type CSSProperties } from 'react';
import { Camera, Gift, Plus, Trash2 } from 'lucide-react';
import { scrubExifMetadata } from '../services/exifScrubber';
import type { StoreItem } from '../data/storeData';
interface Props { items: StoreItem[]; onItemsChange: (items: StoreItem[]) => void; }
const inputStyle: CSSProperties = { width: '100%', border: '1px solid rgba(255,255,255,.16)', borderRadius: 9, padding: 9, background: 'rgba(15,23,42,.65)', color: '#f8fafc' };
export function StoreManager({ items, onItemsChange }: Props) {
  const photoInput = useRef<HTMLInputElement>(null); const [form, setForm] = useState({ name: '', description: '', xpCost: 20, stock: '', imageDataUrl: '' }); const [error, setError] = useState('');
  const upload = async (file?: File) => { if (!file) return; if (!file.type.startsWith('image/')) { setError('Please choose an image file.'); return; } if (file.size > 2_000_000) { setError('Choose an image smaller than 2 MB.'); return; } try { const clean = await scrubExifMetadata(file); if (clean.cleanDataUrl.length > 2_500_000) { setError('That photo is too large after cleaning.'); return; } setForm(current => ({ ...current, imageDataUrl: clean.cleanDataUrl })); setError(''); } catch { setError('That photo could not be used.'); } };
  const add = (event: React.FormEvent) => { event.preventDefault(); const name = form.name.trim(); const xpCost = Math.floor(Number(form.xpCost)); const stock = form.stock.trim() === '' ? null : Math.floor(Number(form.stock)); if (!name || name.length > 60) { setError('Give the reward a name (up to 60 characters).'); return; } if (!Number.isSafeInteger(xpCost) || xpCost < 1) { setError('XP cost must be at least 1.'); return; } if (stock !== null && (!Number.isSafeInteger(stock) || stock < 0)) { setError('Stock must be a whole number or left blank for unlimited.'); return; } const now = new Date().toISOString(); onItemsChange([{ id: `reward_${Date.now()}`, name, description: form.description.trim().slice(0, 280), xpCost, stock, imageDataUrl: form.imageDataUrl || undefined, isAvailable: true, createdAt: now, updatedAt: now }, ...items]); setForm({ name: '', description: '', xpCost: 20, stock: '', imageDataUrl: '' }); setError(''); };
  const update = (id: string, patch: Partial<StoreItem>) => onItemsChange(items.map(item => item.id === id ? { ...item, ...patch, updatedAt: new Date().toISOString() } : item));
  return <section className="store-manager"><div className="manager-card"><h3><Gift size={18}/> Reward catalogue</h3><p className="muted">Only visible and in-stock rewards can be bought by Ufefe.</p>{items.length ? items.map(item => <div className="reward-manager-row" key={item.id}>{item.imageDataUrl ? <img src={item.imageDataUrl} alt=""/> : <span>🎁</span>}<div><b>{item.name}</b><small>{item.xpCost} XP · {item.stock === null ? 'Unlimited' : `${item.stock} in stock`}</small></div><label className="availability-toggle"><input type="checkbox" checked={item.isAvailable} onChange={event => update(item.id, { isAvailable: event.target.checked })}/>Available</label><button onClick={() => onItemsChange(items.filter(entry => entry.id !== item.id))} aria-label={`Delete ${item.name}`}><Trash2 size={16}/></button></div>) : <p className="empty-state">No rewards yet.</p>}</div><form className="manager-card manager-form" onSubmit={add}><h3><Plus size={17}/> Add a reward</h3><div className="form-grid"><input value={form.name} maxLength={60} placeholder="Reward name (e.g. Choose a movie)" onChange={event => setForm({ ...form, name: event.target.value })} style={inputStyle}/><input type="number" min="1" value={form.xpCost} onChange={event => setForm({ ...form, xpCost: Number(event.target.value) })} style={inputStyle}/><input type="number" min="0" value={form.stock} placeholder="Stock (blank = unlimited)" onChange={event => setForm({ ...form, stock: event.target.value })} style={inputStyle}/><textarea value={form.description} maxLength={280} placeholder="A little note about this reward (optional)" onChange={event => setForm({ ...form, description: event.target.value })} style={inputStyle}/></div><div className="reward-photo-row">{form.imageDataUrl && <img src={form.imageDataUrl} alt="Reward preview"/>}<button type="button" className="btn-secondary" onClick={() => photoInput.current?.click()}><Camera size={16}/>Upload photo</button><input ref={photoInput} type="file" accept="image/*" hidden onChange={event => upload(event.target.files?.[0])}/>{form.imageDataUrl && <button type="button" className="text-button" onClick={() => setForm({ ...form, imageDataUrl: '' })}>Remove photo</button>}</div>{error && <p className="form-error">{error}</p>}<button className="btn-primary" type="submit"><Plus size={17}/>Add reward</button></form></section>;
}
