import { useMemo, useState } from 'react';
import { Bell, BookOpen, CalendarDays, Camera, Check, PenLine, Settings2, Sparkles } from 'lucide-react';
import { ShareButton } from './ShareButton';
import { PhotoEvidence } from './PhotoEvidence';
import type { ChoreTask, ScheduleItem } from '../data/scheduleData';
import { getCurrentTermInfo } from '../data/termCalendar';
import { LIFE_SKILLS_WEEKLY_THEMES } from '../data/curriculumData';
import { getATPWeek } from '../data/term4ATP';

interface Props { schedule: ScheduleItem[]; chores: ChoreTask[]; displayName: string; onCompleteChore: (id: string, photo?: string) => void; onOpenDiary: () => void; onOpenProfile: () => void; onRequestNotifications: () => void; }
const time = (value: string) => new Date(`2000-01-01T${value}`).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' });
export function TodayView({ schedule, chores, displayName, onCompleteChore, onOpenDiary, onOpenProfile, onRequestNotifications }: Props) {
  const [photoChoreId, setPhotoChoreId] = useState<string | null>(null);
  const now = new Date(); const todayDay = now.getDay(); const events = useMemo(() => schedule.filter(item => item.dayOfWeek === todayDay).sort((a, b) => a.time.localeCompare(b.time)), [schedule, todayDay]); const active = chores.filter(chore => !chore.isCompleted && (!chore.dueDate || chore.dueDate <= now.toISOString().slice(0, 10))); const completed = chores.filter(chore => chore.isCompleted); const totalXpEarned = completed.reduce((sum, c) => sum + c.xpReward, 0); const minutesNow = now.getHours() * 60 + now.getMinutes(); const next = events.find(item => { const [h, m] = item.time.split(':').map(Number); return h * 60 + m >= minutesNow; }); const greeting = now.getHours() < 12 ? 'Good morning' : now.getHours() < 17 ? 'Good afternoon' : 'Good evening';
  const termInfo = getCurrentTermInfo(); const lifeSkillsTheme = LIFE_SKILLS_WEEKLY_THEMES.find(t => t.term === termInfo.term && t.week === termInfo.week);
  const atpWeekEntries = termInfo.term === 4 ? getATPWeek(termInfo.week) : [];
  const subjectIcons: Record<string, string> = { 'Mathematics': '🔢', 'English Home Language': '📖', 'Afrikaans FAL': '🇿🇦', 'Life Skills': '🌱', 'Coding & Robotics': '🤖' };
  return <section className="today-view"><div className="today-hero glass-card"><div><span className="eyebrow">Your daily adventure</span><h2>{greeting}, {displayName}! {now.getHours() < 17 ? '☀️' : '🌙'}</h2><p>Here is your plan, your wins, and a little space just for you.</p>{completed.length > 0 && <div style={{ marginTop: '10px' }}><ShareButton message={`I completed ${completed.length} task${completed.length > 1 ? 's' : ''} today and earned ${totalXpEarned} XP! 🚀`} subject="Look at my day!" /></div>}</div><button className="avatar-button" onClick={onOpenProfile} title="Make Conquerer yours"><Settings2 size={18}/>Customise</button></div>
    <div className="next-event glass-card" style={{ borderColor: next?.color }}><div><span className="eyebrow">Up next</span>{next ? <><h3>{next.emoji} {next.title}</h3><p>{time(next.time)} · {Math.max(0, Number(next.time.slice(0, 2)) * 60 + Number(next.time.slice(3)) - minutesNow)} minutes to go</p></> : <><h3>🌈 Your planned day is complete!</h3><p>Time for a gentle rest or a fun adventure.</p></>}</div><CalendarDays size={34} color={next?.color ?? '#14b8a6'}/></div>
    {lifeSkillsTheme && <div className="glass-card" style={{ padding: '16px 20px', borderLeft: '4px solid #a855f7' }}><span className="eyebrow" style={{ color: '#c084fc' }}>🌱 This week&apos;s Life Skills theme</span><h3 style={{ fontSize: '1.05rem', color: '#f8fafc', margin: '6px 0 4px' }}>{lifeSkillsTheme.theme}: {lifeSkillsTheme.topic}</h3><p style={{ fontSize: '0.88rem', color: '#94a3b8', margin: 0 }}>{lifeSkillsTheme.description}</p></div>}
    {atpWeekEntries.length > 0 && <div className="glass-card" style={{ padding: '18px 20px', borderLeft: '4px solid #14b8a6' }}><div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '12px' }}><BookOpen size={20} color="#14b8a6" /><div><span className="eyebrow" style={{ color: '#2dd4bf' }}>📚 This Week&apos;s CAPS Learning Focus — Week {termInfo.week}</span></div></div><div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>{atpWeekEntries.map(entry => <div key={entry.subject} style={{ background: 'rgba(15, 23, 42, 0.4)', borderRadius: '12px', padding: '12px 14px' }}><div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '6px' }}><span>{subjectIcons[entry.subject] || '📘'}</span><b style={{ fontSize: '0.9rem', color: '#f8fafc' }}>{entry.subject}</b></div><p style={{ fontSize: '0.85rem', color: '#e2e8f0', margin: '0 0 6px', fontWeight: 600 }}>{entry.topic}</p><ul style={{ margin: 0, paddingLeft: '18px', fontSize: '0.8rem', color: '#94a3b8' }}>{entry.learningOutcomes.slice(0, 2).map((lo, i) => <li key={i} style={{ marginBottom: '3px' }}>{lo}</li>)}</ul></div>)}</div></div>}
    <div className="today-grid"><section className="glass-card schedule-card"><div className="section-heading"><div><span className="eyebrow">Today's timeline</span><h3>📅 What's happening</h3></div><button className="notification-button" onClick={onRequestNotifications}><Bell size={15}/>Turn on reminders</button></div>{events.length ? <div className="timeline">{events.map(item => { const [h, m] = item.time.split(':').map(Number); const status = h * 60 + m < minutesNow ? 'done' : item.id === next?.id ? 'next' : ''; return <div className={`timeline-item ${status}`} key={item.id}><i style={{ background: item.color }}/><span>{item.emoji}</span><div><b>{item.title}</b><small>{time(item.time)}</small></div></div>; })}</div> : <p className="empty-state">No events yet. Dad or Mom can add your plan in Parent Zone.</p>}</section>
      <section className="glass-card chores-card"><div className="section-heading"><div><span className="eyebrow">Little wins</span><h3>✨ Chores & tasks</h3></div><Sparkles size={20} color="#fbbf24"/></div>{active.length ? active.map(chore => <button className="chore" key={chore.id} onClick={() => chore.requiresPhoto ? setPhotoChoreId(chore.id) : onCompleteChore(chore.id)}><span className="chore-check">{chore.requiresPhoto ? <Camera size={15}/> : <Check size={15}/>}</span><span>{chore.emoji}</span><b>{chore.title}</b><em>+{chore.xpReward} XP{chore.requiresPhoto ? ' 📸' : ''}</em></button>) : <p className="empty-state">All clear! You are doing brilliantly. 🌟</p>}{completed.length > 0 && <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginTop: '8px' }}>{completed.slice(0, 5).map(chore => <div key={chore.id} style={{ display: 'flex', alignItems: 'center', gap: '6px', background: 'rgba(20,184,166,.1)', padding: '5px 8px', borderRadius: '10px', fontSize: '.8rem' }}><span>{chore.emoji}</span><span style={{ color: '#2dd4bf' }}>{chore.title} ✓</span><ShareButton message={`I completed my chore "${chore.title}" and earned ${chore.xpReward} XP! ✨`} subject={`I finished: ${chore.title}`} /></div>)}</div>}<button className="diary-quick" onClick={onOpenDiary}><PenLine size={18}/>Write in my diary</button></section></div>
    {photoChoreId && <PhotoEvidence title="Show it's done!" onCapture={photo => { onCompleteChore(photoChoreId, photo); setPhotoChoreId(null); }} onCancel={() => setPhotoChoreId(null)}/>}
  </section>;
}
